require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "script/**/*"
    - "spec/rails_helper.rb"
    - "spec/dummy/db/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Max: 15
